version: '3.1'
services:
  api-reservation-db:
    container_name: api-reservation-db
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_reservation'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3310:3306

  mi-app:
    container_name: phpmyadmin-container
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8085:80
    environment:
      - DB_HOST=api-reservation-db
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge
